"""Check the ported losses against values produced by the original TensorFlow code.

``tests/data/loss_reference_tf.json`` was generated by running the committed
``unet_models.py`` under TensorFlow 2.19.1 (see ``tools/make_loss_reference.py``), so
these assert against the real Keras semantics rather than against a reading of them --
in particular the global (batch-flattened) Dice and the ``K.epsilon()`` = 1e-7 smoothing.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from lst_training import losses as L  # noqa: E402

FIXTURE = Path(__file__).parent / "data" / "loss_reference_tf.json"
# TF reduces in float32 in a different order; the largest reference value is ~9.
ATOL = 1e-5

_data = json.loads(FIXTURE.read_text())
CASES = _data["cases"]
EXPECTED = _data["expected"]

FUNCS = {
    "dice_binary": L.dice_binary,
    "dice_loss_binary": L.dice_loss_binary,
    "tversky_loss_binary": L.tversky_loss_binary,
    "bce": L.binary_crossentropy,
    "bce_dice_loss": L.bce_dice_loss,
    "bce_tversky_loss": L.bce_tversky_loss,
}


def _tensors(case: str):
    c = CASES[case]
    return torch.tensor(c["y_true"]), torch.tensor(c["y_pred"])


@pytest.mark.parametrize("case", sorted(CASES))
@pytest.mark.parametrize("fn", sorted(FUNCS))
def test_matches_tensorflow(case: str, fn: str):
    y_true, y_pred = _tensors(case)
    got = float(FUNCS[fn](y_true, y_pred))
    want = EXPECTED[case][fn]
    assert abs(got - want) < ATOL, f"{fn} on {case}: torch {got!r} vs TF {want!r}"


def test_dice_is_global_not_per_sample():
    """Keras flattens the batch axis, so one Dice covers the whole batch.

    Averaging per-sample Dice would give a different number whenever the samples differ
    in lesion load -- which is the case this guards.
    """
    y_true = torch.zeros(2, 1, 4, 4, 4)
    y_pred = torch.zeros(2, 1, 4, 4, 4)
    y_true[0] = 1.0          # sample 0: full lesion, perfectly predicted
    y_pred[0] = 1.0
    y_pred[1, :, 0, 0, 0] = 1.0   # sample 1: empty truth, one false positive

    per_sample = 0.5 * (float(L.dice_binary(y_true[0:1], y_pred[0:1]))
                        + float(L.dice_binary(y_true[1:2], y_pred[1:2])))
    assert abs(float(L.dice_binary(y_true, y_pred)) - per_sample) > 1e-3


def test_empty_truth_and_prediction_scores_one():
    """The 1e-7 smoothing sits in both numerator and denominator."""
    z = torch.zeros(1, 1, 4, 4, 4)
    assert float(L.dice_binary(z, z)) == pytest.approx(1.0)
    assert float(L.dice_loss_binary(z, z)) == pytest.approx(0.0)


def test_tversky_alpha_penalises_false_negatives_more():
    """alpha = 0.75 weights a miss above a false alarm -- the point of using it here."""
    y_true = torch.zeros(1, 1, 4, 4, 4)
    y_true[..., :2, :, :] = 1.0

    missed = torch.zeros_like(y_true)          # predicts nothing: all false negatives
    over = torch.ones_like(y_true)             # predicts everything: adds false positives

    fn_loss = float(L.tversky_loss_binary(y_true, missed))
    fp_loss = float(L.tversky_loss_binary(y_true, over))
    assert fn_loss > fp_loss
    assert L.TVERSKY_ALPHA == 0.75


class TestDeepSupervisionLoss:
    def test_weights_match_the_training_script(self):
        assert L.DS_WEIGHTS == (4 / 7, 2 / 7, 1 / 7)

    def test_weighted_sum(self):
        crit = L.DeepSupervisionLoss(loss_out=L.dice_loss_binary, loss_ds=L.dice_loss_binary)
        outs = [torch.full((1, 1, 4, 4, 4), 0.6),
                torch.full((1, 1, 2, 2, 2), 0.6),
                torch.full((1, 1, 1, 1, 1), 0.6)]
        tgts = [torch.ones(1, 1, 4, 4, 4), torch.ones(1, 1, 2, 2, 2), torch.ones(1, 1, 1, 1, 1)]
        total, parts = crit(outs, tgts)
        expected = sum(w * L.dice_loss_binary(t, o)
                       for w, o, t in zip(L.DS_WEIGHTS, outs, tgts))
        assert float(total) == pytest.approx(float(expected), abs=1e-6)
        assert set(parts) == {"loss", "out_seg", "deep_supervision_1", "deep_supervision_2"}

    def test_rejects_mismatched_target_count(self):
        crit = L.DeepSupervisionLoss()
        with pytest.raises(ValueError, match="outputs but"):
            crit([torch.zeros(1, 1, 2, 2, 2)] * 3, [torch.zeros(1, 1, 2, 2, 2)] * 2)

    def test_single_output_model(self):
        """ds_layers=() gives a bare tensor, not a list; the criterion accepts both."""
        crit = L.DeepSupervisionLoss(loss_out=L.dice_loss_binary)
        total, parts = crit(torch.full((1, 1, 4, 4, 4), 0.5), torch.ones(1, 1, 4, 4, 4))
        assert set(parts) == {"loss", "out_seg"}
        assert float(total) == pytest.approx(L.DS_WEIGHTS[0] * parts["out_seg"], abs=1e-6)
